#!/usr/bin/env python

import rospy
from controller import DynamicConfigurationParameters


if __name__ == "__main__":
    rospy.init_node("mercury_dynparam", anonymous=False)

    controller = DynamicConfigurationParameters()    
    controller.spin()
