#!/usr/bin/env python

import rospy
from controller import ModeChanger


if __name__ == "__main__":
    rospy.init_node("mercury_mode_changer", anonymous=False)

    controller = ModeChanger()    
    controller.spin()
